### ISSUE TITLE
How to Stretch Vlc Control？

### ISSUE THREAD

**Issue by soapgu** [ZeBobo5/Vlc.DotNet#118]
Just like image control In WPF. it can fill set Stretch property  stretched to fill the destination rectangle.
I do not want display black background in the control.

**Comment by higankanshi** [comment]
Ummm...Maybe you can try my project http://github.com/higankanshi/xZune.Vlc 
They have native WPF control, not a Win32Host.
So it has no airspace issue.

**Comment by soapgu** [comment]
Thanks  higankanshi.
I will try to use your project later.

**Comment by jeremyVignelles** [comment]
This is probably something that is in the scope of #365 . We should probably provide an ImageSource that is separate from the "default" component.

**Comment by jeremyVignelles** [comment]
As of 3.0.0-develop250, the WPF control has been rewritten.
The behavior of the component is to "contain" the video in a ViewBox, so that the image is not stretched.

If you want to stretch, you can probably use an `Image` control, create manually a `VideoSourceProvider` and use its `VideoSource` in you `Image` control. Then, stretch the image as you need.
