### ISSUE TITLE
Synchronize Multiple Recording?

### ISSUE THREAD

**Issue by johnry18** [ZeBobo5/Vlc.DotNet#135]
I have 5 IP(RTSP connection) cameras. I want to record each camera simultaneously. 
The output is saving a record (.mp4 file format) of each cameras with the same length as much as possible.

Bit rate: 2Mb/s
Resolution: 720p30
Continuous Bit rate

**Comment by jeremyVignelles** [comment]
syncing several media is hard. syncing several media from different hardware looks like mission impossible : the timestamps in the streams are likely not synchronized.
you may want to blend the streams in the same file with a mozaic : https://wiki.videolan.org/VLC_HowTo/Make_a_mosaic/
Otherwise, I don't see any way of doing what you want. Anyway, it's not an issue with Vlc.DotNet, so I'm closing this to avoid having too many issues.
Feel free to ask if you need something else.

**Comment by thetiennguyen** [comment]
Sorry, but I have a problem which is not solved although I try some methods. I record video and audio from camera IP via rtsp. However, video is out of sync with audio. Can you tell me some idea to solve it. Thanks a lot. I record stream by using livVLC

**Comment by jeremyVignelles** [comment]
Your issue is not the same, please do not hijack other's closed issues. Open your own with a sample code
