### ISSUE TITLE
Cant play anything

### ISSUE THREAD

**Issue by neoncik** [ZeBobo5/Vlc.DotNet#195]
Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Source: Vlc.DotNet.Core.Interops

Method that throws exception: Vlc.DotNet.Core.Interops.VlcManager.CreateMediaPlayer()

How to fix it ?

**Comment by panchosoft** [comment]
You may be using a "x64" or "Any CPU" application to access VLC in its version x86/32bit. So you need to install the 64-bit version of VLC and point your application to "C:\Program Files\VideoLAN\VLC\" instead of "C:\Program Files (x86)\VideoLAN\VLC\".

It seems that something changed in VLC libraries after version 2.2.1. Try that specific version of VLC if you don't want to change anything in your application.

**Comment by jeremyVignelles** [comment]
Closing old issues, please have a look at the getting started wiki if you need a tutorial.
