### ISSUE TITLE
Unable to import components

### ISSUE THREAD

**Issue by stuntguy3000** [ZeBobo5/Vlc.DotNet#224]
![image](https://cloud.githubusercontent.com/assets/1522389/22821493/3b391af0-efcb-11e6-9c28-82ec8ee1351e.png)

After following the wiki, I am unable to import any of the downloaded dll files for any of the versions. Any ideas? Thanks.

**Comment by mfkl** [comment]
Hi @stuntguy3000 

Try using **AnyCPU** instead of x86 in your path when importing the control.

Also check out https://github.com/ZeBobo5/Vlc.DotNet/wiki/Using-Vlc.DotNet-in-WinForms

**Comment by jeremyVignelles** [comment]
Thanks mfkl for having a look at it. Unfortunately, his path looked right at the time of writing (AnyCPU was introduced very recently by a PR). That being said, maybe this could be caused by using a x86 lib inside a x64 visual studio? In that case, this would disappear with the latest AnyCPU version.
@stuntguy3000, could you try with the latest version?

**Comment by mfkl** [comment]
Visual Studio exists only as a 32bit app so I don't think that's it (if that's what you meant).

For the record, I managed to import the control just fine with the latest version. @stuntguy3000 Do try again, if you still have the issue, please report back here with your configuration (VS version, package version, etc).

**Comment by stuntguy3000** [comment]
I will try to give this a shot in the coming days, been a while since I attempted it.

**Comment by jeremyVignelles** [comment]
Any update here? May I close the issue?

**Comment by stuntguy3000** [comment]
I no longer have the capacity to solve this so I do not know if the issue is solved.

For all intensive purposes, this is done.
