### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by swift11** [ZeBobo5/Vlc.DotNet#225]
VLC on Samsung TV would be great :)
https://developer.tizen.org/development/tizen-.net-preview

https://developer.tizen.org/development/tizen-.net-preview/introduction/overview

**Comment by jeremyVignelles** [comment]
Interesting idea. Do you own a samsung TV? Would you like to contribute to this project?

**Comment by jeremyVignelles** [comment]
First step done : Vlc.DotNet is now .netstandard compatible 🎉

**Comment by swift11** [comment]
Please note: .NET will run on 2018 models https://wiki.tizen.org/Devices#TV

**Comment by jeremyVignelles** [comment]
Only on 2018 models? the current models can't run .net or is it just a matter of firmware upgrade?

**Comment by swift11** [comment]
.NET will run on Tizen 4 (2018 models), we don't know if Samsung will extend it on Tizen 3 (2017 models)
http://developer.samsung.com/tv/develop/specifications/tv-model-groups

**Comment by swift11** [comment]
published yesterday: _Xamarin Forms TV App Development for Tizen_
https://channel9.msdn.com/Events/dotnetConf/2017/T217

**Comment by jeremyVignelles** [comment]
I'm closing this since there's little chance that this will be done in Vlc.DotNet now that https://github.com/videolan/libvlcsharp is on the tracks.

You can probably either post an issue there : https://code.videolan.org/videolan/LibVLCSharp/issues or make the PR yourself. Don't hesitate to ask for help there ! :)
