### ISSUE TITLE
Useless and incompatible as of 2017

### ISSUE THREAD

**Issue by masiton** [ZeBobo5/Vlc.DotNet#235]
This component is unable to:

- Play a stream
- Support VS designer (your preview will not work as long as you use this component)
- Fullscreen
- Mouse operations over the video control

Also has very little documentation, no working samples, doesn't build upon download of repo, author doesn't respond to people's tickets.

If you're looking to implement any of the abovementioned features, save yourself some time and don't make same mistake I did. Use different library.

**Comment by AdamLytx** [comment]
It can play a stream. I edited the VLC.DotNet.Wpf.Samples (.net 4.5) , set as startup project.  The sample does work, if you compile the whole project.

  string opts = ":network-caching=4000";
            myControl.MediaPlayer.Play(new Uri("rtsp://--someIpAddressOfRtsp/live2.sdp"), new string[1] {opts });

Full screen is an issue, apparently awaiting on a pull request.  A bigger one is lack of an example using MVVM style bindings.

**Comment by thephez** [comment]
I have been using this for several months and have not found it to be either useless or incompatible.  Sure there are some things it doesn't do, but full screen and mouse operations can be handled other ways.  And the MIT license makes it usable for situations where some other options are not practical.

**Comment by jeremyVignelles** [comment]
Hi, I am a new collaborator for this project. I agree with you with some of the points you mentionned:
- Mouse operations does not work well for many users, we will have to look at it
- Little documentation, but I have created a Getting Started wiki since then.
- Author does not respond to people's tickets : As many open source project created by individuals, time is often lacking to support the project you are working on. That's why we need a community around this project, and that's why I asked him to get involved.

This library is not the perfect library I'd love to use, but it does exist and saved me some time to create my app. Sure, I did have issues getting it started, but I now share my knowledge and contribute back to this project.

If something is missing, please open a specific issue to ask for that feature (but don't expect a quick implementation). Even better, make pull requests to contribute to that project. If you don't like the way it's done, find another project or fork this one, but in the end, it's all about contributors.

Please keep an eye on this project and see how things goes in the future.
