### ISSUE TITLE
Obtaining Video Resolution & FPS info

### ISSUE THREAD

**Issue by donaldjduck** [ZeBobo5/Vlc.DotNet#243]
The interactive version of VLC exposes video codec data such as resolution, fps etc.  I am using VLC.DotNet nuget library 2.1.134 / net45 / x86 in a Forms application and haven't been able to find references to such data under VLCControl, VLCControl.Video, VLCControl.GetCurrentMedia objects. 

Can anyone suggest where such data can be found, please?

**Comment by thephez** [comment]
Check out [this example code](https://github.com/ZeBobo5/Vlc.DotNet/blob/master/src/Samples/Vlc.DotNet.Forms.Samples/Sample.cs#L125) from the samples folder in the repository.

`
var mediaInformations = myVlcControl.GetCurrentMedia().TracksInformations;

            foreach (var mediaInformation in mediaInformations)
            {
                if (mediaInformation.Type == Core.Interops.Signatures.MediaTrackTypes.Audio)
                {
                    myLblAudioCodec.InvokeIfRequired(l => l.Text += mediaInformation.CodecName);
                    myLblAudioChannels.InvokeIfRequired(l => l.Text += mediaInformation.Audio.Channels);
                    myLblAudioRate.InvokeIfRequired(l => l.Text += mediaInformation.Audio.Rate);
                }
                else if (mediaInformation.Type == Core.Interops.Signatures.MediaTrackTypes.Video)
                {
                    myLblVideoCodec.InvokeIfRequired(l => l.Text += mediaInformation.CodecName);
                    myLblVideoHeight.InvokeIfRequired(l => l.Text += mediaInformation.Video.Height);
                    myLblVideoWidth.InvokeIfRequired(l => l.Text += mediaInformation.Video.Width);
                }
}
`

**Comment by donaldjduck** [comment]
That's exactly what I needed for Resolution and other Codec info.  Many thanks.

I presume Issue #206 still being open means FPS is still not available...?

**Comment by donaldjduck** [comment]
Concerning 4CC... not so cryptic apparently: a quick Google of 4CC yields https://www.fourcc.org/fourcc.php where it defines what 4CC is.  The integer value 875967080 converts to hex as 34353268 (as it was open on my desktop, I used MS Excel's DEC2HEX function).  This is the 4x ASCII chars "462h", which, when read little-endian becomes "h264" - no surprise I think.  As you'll see under Codecs under that page, there is quite a list.

**Comment by Videstra** [comment]
Mr Duck - you win the Internets today Sir!

**Comment by jeremyVignelles** [comment]
In case someone is still interested in 4CC : 
4CC is just a 4 byte (= ascii character) array that contains an identifier. It is used everywhere in VLC, and notably for video codec identification.

If the 4CC of your codec is "MP4V", then it will be written as [ 0x4D, 0x50, 0x34, 0x56 ]. If you try to interpret this as an integer, it will give you an awfully unreadable unsigned integer value (0x4D503456).
More problematic, the value you read depends of the endianness of your Operating System (Big-Endian or Little endian)

4CC should be serialized as string rather than integers in my opinion, or even better, as a 4CC struct/class. Please open issues for that if you find this kind of things.
