### ISSUE TITLE
Black Command Line Screen for Logs

### ISSUE THREAD

**Issue by gaitanivan** [ZeBobo5/Vlc.DotNet#248]
Hi everybody.

I use this project, I add three projects (forms, core, core.interops) to my project, add references, compile and work, but, when I run in development PC in Debug, I saw a black command line window showing me logs, this screen appears when I show the win form that contains the vlcControl user control, but when I run in Release that black command line window no shows.

I build the project in Release, create installer, run installer in another PC and when show the form, the black screen appears again.

How to hide, delete, destroy, no show or any else. How I do to remove that black screen????

**Comment by TobiasSpatt** [comment]
Hi,

You can remove the console window by adding a "--quiet" media option.

Regards Tobias

**Comment by jeremyVignelles** [comment]
By looking at the source code, I can confirm that TobiasSpatt said : Adding an option before EndInit solves the issue.
In fact, passing any option array as `VlcMediaplayerOptions` should do the trick, even like this:

```
            myControl.MediaPlayer.VlcMediaplayerOptions = new string[0];
            myControl.MediaPlayer.EndInit();
```

The reason is that, for debugging purpose, If you do not specify anything (`null` option), the following options will be applied : 
```
new[]
            {
                "--extraintf=logger",
                "--verbose=2"
            }
```

In release mode, the `--quiet` option will be given.
