### ISSUE TITLE
Theora codec issue 

### ISSUE THREAD

**Issue by SheetalRaj** [ZeBobo5/Vlc.DotNet#262]
Hi There, 

Has anyone been successful to use Theora video code ?
When I start streaming  from C# application using "Theora" codec
"sout=#transcode{vcodec=theo,vb=800,acodec=vorb,ab=128,channels=2,samplerate=44100}:rtp{sdp=rtsp://"+stramingOutPoint+"}"

I can view the stream in VLC player but not in C# application. Have tried other way around but still can't see the stream and when i try to close C# application it get stuck on " vlcControl_Local.Stop()"and doesn't exit.

Anyone got a clue what is wrong going here?

Thanks

**Comment by jeremyVignelles** [comment]
I'm not really an expert, but I have found something that looks weird to me. You are using a VlcControl, which is about displaying, but you are giving VLC options to stream the video.
My suggestion would be to try with only Vlc.DotNet.Core, since you don't seem to use the video display.

Also, does this behaviour happens only with theora?
