### ISSUE TITLE
VLC.Dotnet.Forms.dll is invalid file

### ISSUE THREAD

**Issue by Symbai** [ZeBobo5/Vlc.DotNet#270]
I cannot add the dll file to my tool box. I've tried x86 and x64 in Visal Studio 2017 and each time I try, I get the error message.
![devenv_2017-07-06_01-11-24](https://user-images.githubusercontent.com/14368203/27888754-35fd10d4-61e8-11e7-9e97-c6692dcaaa45.png)

**Comment by jeremyVignelles** [comment]
You should try using the Vlc.DotNet.Forms package with NuGet rather than downloading the files directly.

Regarding your message, it looks like something is broken on your side. It could be the file or visual studio. You could try opening the file with JetBrain's dotPeek and see if the file is really valid
