### ISSUE TITLE
Release notes / Changelist

### ISSUE THREAD

**Issue by SkinnySackboy** [ZeBobo5/Vlc.DotNet#282]
Given there appear to not be any tags for the most recently released versions, is there somewhere I can check what has gone into each version?

Thanks,

Mark

**Comment by jeremyVignelles** [comment]
Not at the time being, this is something we need to have in future version. At the time being, you can have a look at the commits in master : https://github.com/ZeBobo5/Vlc.DotNet/commits/master . My guess is 1 commit = 1 minor version increment since appveyor publishes a new package for each push into master

**Comment by jeremyVignelles** [comment]
There is now a [Changelog](https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/CHANGELOG.md)

**Comment by SkinnySackboy** [comment]
Thank you very much, this is perfect!
