### ISSUE TITLE
Updating vlc lib to 2.2.2 from 1.1.5

### ISSUE THREAD

**Issue by remy33** [ZeBobo5/Vlc.DotNet#283]
Hello, the version using in the project is slightly old,
I had some time trying to append and use logo with videos with mp4 container, also green screen at the begining.
I have found this: https://github.com/wearenocomputer/libVLC-32BitCompiledWindows
And copied the default (2.2.6) GUI 'plugins' directory and it solve most of the problems.
If someone has some spare time and he could upgrade the version it would be very usefull.
Have a good day.

**Comment by jeremyVignelles** [comment]
Hi,
You should only be using the library files from the official VLC distribution : 

I created recently [a "getting started" wiki page](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started)  where I describe the process of downloading the library.

I don't recommend using the library files in the Vlc.DotNet repository

**Comment by remy33** [comment]
Hello,
Thank for the effort.
I actually did it a while ago and just few days ago ( after finish the
project ) I found the time to open the case.
Anyway, then I tried to do the steps you mentioned and it didn't work as
expected ( bugs ) or made memory exceptions.
But even if it's fixed now, still it would have be nice if someone will
make a pull request with updated Library so the Nugget package would be
updated.
It's important to get above the 2.2.x version due to x264 transcoding bugs
and video ending early bugs which according to Remy ( not me but one of VLC
Devs :-) has fixed.

**Comment by jeremyVignelles** [comment]
Hi,
I am currently using a nightly version of VLC 3.0.0 with this library and it works like a charm. If not, maybe we could try to help you with that if you give us more info.

I'm don't think it is a good idea to make the PR as you requested, for the reasons I exposed in #288. Mainly : This library is independant of the version of VLC you are using, and providing a version would make people think that this is the only compatible version. Moreover, adding binary files adds weigh to the repository which can quickly become heavy... But I'm not the maintainer of this project.

**Comment by remy33** [comment]
Well, right, there is the sample project and also you created a get started
section.
But I think as for the .NET way is to provide a practical working library
rather then give you an abstract version in which you have to compile
following confusing manuals as Linux programmers love.
Plus, maybe it changes now due to the commit three weeks ago, but I don't
want to check and change things now as my project is done.
Anyway, if it's working now, I don't see a reason why not update it. You
can argue if you should remove the bins, but as long as it here, it better
be updated.

**Comment by jeremyVignelles** [comment]
You are right, we can't ask a .net developer to build a VLC version by itself (tested it myself, had bad times :laughing: ). Maybe we should have a NuGet package somewhere that provides prebuilt versions of the VLC library? That way, you could install everything "the .net way". What do you think about it?

**Comment by remy33** [comment]
Yes, Nuget package depency is the right and clear solusion.
It's also provide the right way to update the dlls without touch the wrapper itself.
side note: You're doing amazing jobe, thank you.

**Comment by bbougot** [comment]
If you are interested, I have made a NuGet package for VLC libs here : https://www.nuget.org/packages/VlcLibs/

**Comment by jeremyVignelles** [comment]
@bbougot I have indeed seen your package on NuGet, but I have several remarks:
- We don't know whether it is a x86 or x64 library
- The dll files are in a net45 subfolder, but what about a .net 3.5 project ? (.net 3.5 and 2.0 seems to be supported by Vlc.DotNet, so we need a dependency that can be installed on such projects)
- The link you provide in your is the link of videolan rather than the link to your repository. As a security-aware developper, I want to know exactly what is being installed, especially when using native libraries packaged by a developer I never heard of.

What I'd like:
- NuGet packages that are directly provided by VideoLan if possible (I sent them an e-mail through their mailing list)
- One NuGet package per processor architecture/OS (my secret plan : port Vlc.DotNet on linux/rasp)
- Have this package available for any .net version. This link may help : https://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory

I suggest that we continue this discussion in #288

**Comment by jeremyVignelles** [comment]
Closing this in favor of the proposal at #288 .
@bbougot : I had an answer from VideoLan, please see #288
