### ISSUE TITLE
Using the libraries embedded instead of via a library path

### ISSUE THREAD

**Issue by janpieterz** [ZeBobo5/Vlc.DotNet#30]
Hi,

I need to develop a DLL that has the capabilities of decoding h264 from a certain source. This means I won't be able to install the VLC library files in a specified folder (this piece will be embedded in a bigger application without this kind of control, see it as an extension). I was wondering if you guys would be up for the idea of a changed library initialization where by using for example https://github.com/Fody/Costura we allow the libraries to be gathered from not just a path but also the already loaded assemblies or simply the current executing path.
Maybe this is already possible but the docs seem to point in a different direction.
Would be up for helping along!

**Comment by sepehr1014** [comment]
Hi,
If I'm not mistaken by "or simply the current executing path" you mean you want to have VLC libraries in the executable file directory. That's the case when you download the source files. You can copy VLC libraries in the executable path and provide that directory to VLCMediaPlayer.

**Comment by janpieterz** [comment]
But the need to have them embedded within an executable is impossible I assume, since the plugins folder needs to be copied as well?

In my use case I only need them embedded.

**Comment by sepehr1014** [comment]
I don't know if the libraries can be used directly from memory, but one way around would be to embed the files in the executable and offload them to a temporary location ...
Also pay attention to each library and plugin's license.

**Comment by janpieterz** [comment]
Thanks! This will sadly be a little bit too time-intensive and resource intensive (users will click very quickly between different video sources and only then my code gets initialised). Besides that I haven't  been able to get Vlc.DotNet to work with an RTSP stream (either directly or a version streamed to disk). Weird use case and now I'll have to hunt for  a good in-code decoder.
Wrong place to ask perhaps but do you or anyone else know a good resource?
https://github.com/soywiz/cscodec does the job but with a lot of artefacts compared to VLC and we haven't been able to find something comparable.

**Comment by sepehr1014** [comment]
I don't know about RTSP, but I've successfully built an "Online TV" app playing RTMP streams using the old version of VideoLan Dot Net available at https://vlcdotnet.codeplex.com/
It may be worth trying. (Although you'll still need VLC library files)
As a side note I highly recommend playing m3u8 playlists if available instead of directly playing the RTMP stream. VLC supports them too.

**Comment by janpieterz** [comment]
Interesting, thanks for your thoughts.
In this case I'll be reading RTSP streams from a live source that is not under my control (a NVR having up to 64 cameras connected). Quite a limited environment. 

As far as I know RTMP and RTSP are just two different ways of achieving the same thing, streaming media. RTSP uses RTP as it's underlying protocol and adds a little layer (very much like http) where certain information can be gained and commands can be executed, like discovering which codec streams are available at a certain endpoint and setting which one your application prefers for example.

Just out of curiosity and to broaden my understanding of this subject, why do you say you'd recommend m3u8 over directly playing RTMP?

**Comment by sepehr1014** [comment]
RTSP seems interesting!
I recommend m3u8 not for technical reasons (actually I don't have deep understanding in this matter) but because of VLC's behavior. When you directly play RTMP streams in VLC Media Player (which uses the same VideoLan libraries), stopping the stream, freezes the media player for a shot time (at least in version 2.1 and earlier). I've seen better performance and more stable behavior with m3u8 playlists in VLC.

**Comment by janpieterz** [comment]
Thanks, nice practical insight!
