### ISSUE TITLE
Video stuttering but works in vlc

### ISSUE THREAD

**Issue by evo744** [ZeBobo5/Vlc.DotNet#341]
# Generic information

- **Vlc.DotNet version** : 2.2.2-develop225 (last at the time), also tried 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64, nigtly
- **.net version** : 4.5
- **Project language** : VB.net
- **Project build architecture** : AnyCPU (x64)
- **Operating system** : Windows 10 x64

# Summary

Video Information

Type: Video
Codec: MPEG-H Part2/HEVC (H.265) (hevc) 
Resolution: 1920x1088
Display resolution: 1920x1080
Frame rate: 23.976215
Decoded format: Planar 4:2:0 YUV 10-bit LE

Type: Audio
Codec: A/52 B Audio (aka E-AC3) (eac3)
Language: English
Channels: Stereo
Sample rate: 48000 Hz
Bits per sample: 32

Video stutters constantly (audio works)
- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Video stuttering is often caused by a long call made in a VLC callback or event (log already has a protection for that). Could you check that you do not have any callbacks that could cause that? If yes, the solution might be to run your code on a different thread, like in ThreadPool.QueueUserWorkItem.

Also, does this issue only happen when the project is run when debugging in Visual Studio?

**Comment by evo744** [comment]
I don't have any callbacks like that and ThreadPool helped, but something weird that I tested is if I use the vlc lib from the last stable version 2.2.6 (32bit, 64bit didn't want to work) the problem was gone. I don't think is the projects fault here, I think is vlc, using the last nightly there is a very small shutter sometimes. Weird...

**Comment by jeremyVignelles** [comment]
Did that get any better with VLC 3?

**Comment by jeremyVignelles** [comment]
Still having this issue? Feel free to reopen if needed
