### ISSUE TITLE
System.componentModel.Win32Exception 

### ISSUE THREAD

**Issue by Farliam** [ZeBobo5/Vlc.DotNet#343]
Hello at all,

I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1.0
- **Vlc.DotNet project used** : (WinForms/WPF/Core)
- **libvlc version** : (2.2.5.1) (x86/x64) + how did you get it?
- **.net version** : 4.6.2
- **Project language** : (VB.net)
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows 10 Pro) (x64)

# Summary
I have always the error : System.componentModel.Win32Exception : %1 is not a valid Win32 application
VlcLibDirectory is ok and checked.

# Detail
L'exception System.ComponentModel.Win32Exception s'est produite
  HResult=0x80004005
  Message=%1 n’est pas une application Win32 valide
  Source=Vlc.DotNet.Core.Interops
  
- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Please check that you are using x64 vlc library with a 64 bits projects or the other way around.

**Comment by Farliam** [comment]
I have only one library.
I tried another way from a blank project and it's working good.
But with the same settings, VLC control doesn't work in my project... very curious. I don't understand the difference.

**Comment by jeremyVignelles** [comment]
Under the project settings, in the build settings, what is the target architecture? x86, 64, AnyCPU? If this is AnyCPU, Is the "prefer 32 bits" box checked?

**Comment by Farliam** [comment]
Yes !! I haven't seen this little detail. It work now
I must try in production mode because we have only x64 machines. This software need lot of memory. 
last question : is there possible to build it without "prefer 32 bits"
Thank you for your help Jeremy. 🥇

**Comment by jeremyVignelles** [comment]
Here is my explanation of the target architecture options:
- x86 : Your application will only work in 32 bits mode
- x64 : Your application will only work in 64 bits mode (i.e. will not work on 32 bits OS)
- AnyCPU : Your application is built so that its code can be run on x86 and x64 platforms. If you tick "prefer 32bits", then it will run in 32bits in priority and, if the OS doesn't support 32bits, will run in 64bits. (I don't know of any OS that doesn't support 32 bits, even windows 64bits supports 32 bits applications)

That being said, you need to keep in mind one thing : those options are made for .net assemblies, which are compiled into IL (intermediate language) before being interpreted by the .net runtime.

Vlc.DotNet relies on a native library (libvlc), which is built only for 32 bits or only for 64 bits. You must choose the correct libvlc bitness depending on the process' bitness.

You now have a few options:
- Choose x86 or x64, and redistribute 32bits or 64bits libvlc accordingly. x86 will be able to run on all windows, x64 only on 64 bits windows
- Choose AnyCPU but keep "prefer 32bits" and use 32bits libvlc with that
- Choose AnyCPU without "prefer 32bits", As explained below

I personally prefer the last solution even if that means more work and more testing : It feels like a hack to me to use 32 bits application on a 64 bits system, even if that works.
If you do that, you will need to check the process bitness to choose the correct library, as explained in the Getting Started wiki:

```
            if (IntPtr.Size == 4)
            {
                // Use 32 bits library
                libDirectory = Path.Combine(Environment.CurrentDirectory, "libvlc_x86");
            }
            else
            {
                // Use 64 bits library
                libDirectory = Path.Combine(Environment.CurrentDirectory, "libvlc_x64");
            }
```

Side note that seems obvious for me but might not be obvious for everyone: 32 bits processes uses 32 bits adresses, i.e. 4 octets adresses, whereas 64 bits uses 8 octets adresses (64 bits). By testing the size of a pointer, we can detect whether this process is running in 32 bits mode or in 64 bits mode.

Good luck!
I'm closing this since your initial question has been resolved

**Comment by Farliam** [comment]
Hi, still me...
Other issue with this control.
Into playing event, I write this code...:

```
    Private Sub VlcControl1_Playing(sender As Object, e As VlcMediaPlayerPlayingEventArgs) Handles VlcControl1.Playing
        Dim mediaInformations As Object = VlcControl1.GetCurrentMedia().TracksInformations
        For Each mediaInformation As Object In mediaInformations
            If mediaInformation.Type = Vlc.DotNet.Core.Interops.Signatures.MediaTrackTypes.Audio Then
                myLblAudioCodec.Text = mediaInformation.CodecName
                myLblAudioChannels.Text = mediaInformation.Audio.Channels
                myLblAudioRate.Text = mediaInformation.Audio.Rate
            ElseIf mediaInformation.Type = Vlc.DotNet.Core.Interops.Signatures.MediaTrackTypes.Video Then
                myLblVideoCodec.Text = mediaInformation.CodecName
                myLblVideoHeight.Text = mediaInformation.Video.Height
                myLblVideoWidth.Text = mediaInformation.Video.Width
            End If
        Next
    End Sub
```

I receive this message : Invalid inter-threads operation : The control "myLblVideoCodec' accessed from a thread other than the one on which it was created.
I try many test and this error appears for each events of VlcControl (Playing - Paused - PositionChanged - Stopped and more...)
Why ?
This is the same thread !

**Comment by jeremyVignelles** [comment]
This is one of the recurring issues we need to address sometime : 
When you are in a libvlc callback, you are in the vlc thread. In other words, the time you spend on that thread delays the video playing.
You need to explicitely change the thread you are in so that vlc continues to execute normally. This should be done in the Vlc.DotNet in my opinion.

You can execute your work with the `ThreadPool.QueueUserWorkItem` method
