### ISSUE TITLE
New Event for VlcControl 

### ISSUE THREAD

**Issue by 01001001** [ZeBobo5/Vlc.DotNet#380]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.1.0)
- **Vlc.DotNet project used** : WinForms
- **.net version** : (>= 4.5)
- **Project language** : (VB.net)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10 Ent.) (x64)

# Summary

It would be great to have an event that will be triggered as soon VlcControl.state is changing.
In my case I have a Form with an StatusBar, here I could easily add a label that show always actual state of VlcControl like Playing, Buffering....

**Comment by jeremyVignelles** [comment]
You can handle all events individually (Opening, Buffering, Playing...) and call what needs to be called on such event. I agree that a "State changed" event would make this task easier, but I'm not sure that this is a good thing for Vlc.DotNet to implement, because libvlc itself does not implement it, and we're just a binding over libvlc.

**Comment by 01001001** [comment]
You are right, it is not the best solution. But maybe better as implementing "features" that are not available OOTB.
I will close this topic, many thanks for your help.
