### ISSUE TITLE
Aspect Ratio of 16:9 DVD movies always displayed in 4:3

### ISSUE THREAD

**Issue by ew16** [ZeBobo5/Vlc.DotNet#386]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0 develop 261
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.1 x86
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 7 and 10 - x64

# Summary

I have a lot of mkv-movies in 16:9 aspect ratio (from DVD - anamorphic 16:9 with a resolution of 720x576).
They are displayed in VLC Player and Vlc.DotNet.Forms in the correct 16:9 aspect ratio AUTOMATICALLY.
Using Vlc.DotNet.Wpf these movies are always displayed in the wrong 4:3 aspect ratio.
I've checked this wrong behaviour also with your samples applications.
Same result - with Forms correct - with WPF incorrect.
Am I doing something wrong ?
Do I have to specify in WPF some additional options for the MediaPlayer class ?
Thank you
Bye
Erwin

**Comment by jeremyVignelles** [comment]
Hi,
Sorry for the delay, I was doing something else when I received your e-mail and totally forgot to reply.

This is a case I never tested when I implemented the Wpf control. When I try to get the file ratio, I divide the width by the height here : https://github.com/ZeBobo5/Vlc.DotNet/blob/eda62b2cec210161aa9ea7b40029185bb72dcae4/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs#L128

I don't know if I have any other options for that. Maybe this is related to #375 : We may need to add a AspectRatio property somewhere so that we can override the aspect ratio.

Do you have a small sample file that can demonstrate that behavior, so that I can take actions to mitigate that?

**Comment by ew16** [comment]
Here is a 3sec sample file.
[AAA.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/1784317/AAA.zip)
Bye
Erwin

**Comment by jeremyVignelles** [comment]
From what I've seen, the issue is more serious than expected : 
When I'm in the `VideoFormat` callback I know the width/height in pixels, but not the "target" aspect ratio. I think that an info is missing in libvlc to reliably get that info. We could just get the first track and get its aspect ratio, but that feels terribly wrong (there might be more than one video track).

I'll ask what VLC developers think about that, but I don't expect anything before VLC 4.0.0... In the meantime you have several options:
- Use WinForms in your Wpf control
- Use an Image which you set at the correct aspect ratio, and wire the things yourself, as suggested in #375 .

**Comment by ew16** [comment]
Hello Jeremy,
I think there must be some kind of a flag (Anamorphic-Flag) in the video-stream or libvlc. If this flag is set the video must be stretched horizontally. According to the resolution the aspect ratio is correct.
Bye
Erwin

**Comment by jeremyVignelles** [comment]
VLC itself knows what is the aspect ratio and scales accordingly in other vout modules, but the "vmem" video output module doesn't pass that info to my callback, so I really don't know how to solve that issue.

**Comment by jeremyVignelles** [comment]
Or maybe is there a bug in the vmem plugin : The dimensions passed here might need to take the aspect ratio into account?

**Comment by jeremyVignelles** [comment]
Found [this issue](https://trac.videolan.org/vlc/ticket/8122#no3) while trying to fix your bug in #526 , stay tuned.
