### ISSUE TITLE
replacement for SourceProvider in Vlc.DotNet version 2.2.1

### ISSUE THREAD

**Issue by indra1602** [ZeBobo5/Vlc.DotNet#393]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64
- **.net version** : 2015
- **Project language** : C#
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : Windows 10 x64

# Summary

is there a replacement for SourceProvider in Vlc.DotNet version 2.2.1 because I have confusion in working on my project, please help

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hello,
I'm sorry about the confusion. The thing that you see on github is the development branch, which is on the road for 3.0. The master branch has the code that is released in NuGet.

the WPF control has been rewritten in 3.0.0 . The 2.2.1 control is just a wrapper around the Vlc.DotNet.Forms,and doesn't support the new things that you can do with SourceProvider.

You have several options here:
- Use the new 3.0.0 version, keeping in mind that it's still in prerelease, and that API might change before the released version.
- Use the 2.2.1 WPF control. I wouldn't recommend this approach since you will need to rewrite everything when 3.0.0 will be released
- Use the 2.2.1 WinForms control, which is what 2.2.1 WPF did anyway. It will have better perfs than 3.0.0 WPF (do your own benchmarks), and you will be able to upgrade easily on 3.0.0 since the WinForms API won't change much (I hope)

**Comment by jeremyVignelles** [comment]
Feel free to come on gitter if you have more questions.
