### ISSUE TITLE
Calling .Pause twice resumes playing

### ISSUE THREAD

**Issue by mterwoord** [ZeBobo5/Vlc.DotNet#454]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0-develop296
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : (Please fill) (x86) + Copied them from a vlc zip file
- **.net version** : 4.5.2, running on windows 10
- **Project language** : VB.net
- **Project build architecture** : x86/
- **Operating system** : Windows 10 x64

# Summary

Calling VlcControl.Pause twice resumes playback.

**Comment by morl0048** [comment]
I think this is supposed to be happening... It resumes the playback with a delay! (:

**Comment by jeremyVignelles** [comment]
I asked him to post an issue there. I think we should change this misleading behaviour:
We should be calling [libvlc_media_player_set_pause(true)](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga6e39882b33a22337cec9fd49dd7e23c4) instead of [libvlc_media_player_pause](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga61712d4eb8f63232c712a81fb19ee8fa)

Comments welcome :)

**Comment by jeremyVignelles** [comment]
I decided to add a new API to stay aligned with libvlc functions and to keep compatibility with older versions of Vlc.DotNet. What do you think about #471 ?
