### ISSUE TITLE
CropGeometry not working from 3.0.0 onwards

### ISSUE THREAD

**Issue by arkadiuszrutkowski** [ZeBobo5/Vlc.DotNet#458]
# Generic information

- **Vlc.DotNet version** : 3.0.0-develop296
- **Vlc.DotNet project used** : Vlc.DotNet.Wpf
- **libvlc version** : 3.0.3 x64 from official ftp (https://download.videolan.org/pub/videolan/vlc/3.0.3/)
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

I'm testing out newest develop build and I've noticed `VlcControl.SourceProvider.MediaPlayer.Video.CropGeometry` property doesn't have any effect on running stream (neither RTSP nor UDP). This issue doesn't appear in earlier Vlc.DotNet versions (below 3.0.0).

Tested out with VLC 3.0.3 (app) and cropping works fine.

**Comment by jeremyVignelles** [comment]
This can be normal on the WPF control, I guess, since video output is handled differently. If you would like to keep the current behavior and perfs of your app, I'd recommend that you use the WinForms control in a WinFormsHost instead

**Comment by arkadiuszrutkowski** [comment]
Unfortunatelly I can't do that due to experiencing issues with https://github.com/ZeBobo5/Vlc.DotNet/issues/427 .

Anyway what I REALLY want to achieve is implementing one requirement - handling UDP timeouts. What I've researched is libVLC 3.0.0 introduced --udp-timeout parameter. However due to above issue I can't use it.

Other approach was taking periodically snapshots from UDP stream and compare them pixel wise so I can determine that in following repeating snapshot sequence there's timeout. However as described in issue https://github.com/ZeBobo5/Vlc.DotNet/issues/445 there's little lag during saving snapshot to file and even moving to other thread causes short noticable stutter.

Is there any other way to determine UDP timeouts?

**Comment by jeremyVignelles** [comment]
I'm really confused about what you're saying.
I want to clarify one thing : You can use libvlc 3.0.x with Vlc.DotNet 2.2 : Vlc.DotNet is now independent of the libvlc version used. I'd recommend that you use libvlc 3.0.x in all your developments, since the libvlc 2.x branch is officially unsupported.

You have this issue, with CropGeometry. Vlc.DotNet.Wpf might not be impacted by that parameter, and that's why I'm suggesting that you use the WinForms control to overcome this limitation.

Issue #427 Is another thing and you closed it. Maybe we should reopen it?
Many directX-related fixes have been pushed recently in libvlc, and maybe one of them can fix your issues? Version 3.0.4 should come in the following days and will contain some of those fixes. In the meantime, you can download the latest libvlc nightly and try it.

I don't think that taking snapshots is the best option here.

**Comment by arkadiuszrutkowski** [comment]
Maybe you're right. Rather than fixing root cause I'm more like fighting symptoms. Ok I've actually discovered right now new clue which I couldn't notice at the first time so maybe we should close this issue and continue conversation inside #427 ?
