### ISSUE TITLE
libvlc error in windows (x64)

### ISSUE THREAD

**Issue by leooshad** [ZeBobo5/Vlc.DotNet#503]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (2.2.1)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (Please fill) (x86) 
- **.net version** : (4.0)
- **Project language** : (VB.net)
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows 7) (x86/x64)

# Summary

hello again

i have a question in vlc lib directory

when i add the libvlc (x86) into my project and run in windows(x86) works good and without error

now if i run it in windows (x64) the app crashed i must to change the libvlc to (x64) to work on this system 

the question is there any method to put the same libvlc and run app in system (64) and (86) ???

So that I do not have to make two copies of my program one for (x64) and one for (x86)

code i puted in my project:

Private Sub VlcControl1_VlcLibDirectoryNeeded(sender As Object, e As Vlc.DotNet.Forms.VlcLibDirectoryNeededEventArgs) Handles VlcControl1.VlcLibDirectoryNeeded
        Dim aP As String

        If Environment.Is64BitOperatingSystem Then
            aP = Path.Combine(Application.StartupPath & "\lib\VLC")
        Else
            aP = Path.Combine(Application.StartupPath & "\lib\VLC")
        End If
e.VlcLibDirectory = New DirectoryInfo(aP)
End Sub

thank you

**Comment by jeremyVignelles** [comment]
No there's no way to redistribute a universal libvlc for x86 and x64, because of the way the OS works : when you're in a 32 bits process, you can't load a 64 bits DLL and the other way around.

There is a .net-only thing that is called AnyCPU. this is a way to make a DLL independant of the bitness, and that lets the CLR decide at runtime. However, in the end, it will always be a 32 or 64 bits process.

Here are a few ideas :

- Only redistribute 64 bits libvlc and build your app for x64, dropping support for x86 because there's no more x86 windows nowadays [ref needed]
- Only do the same thing for x86, all windows x64 include the compatibility layer to use x86 programs, so you'll be fine until the support for that is dropped
- Use both, but selectively copy plugins that you need, refer to the mfkl/libvlc-nuget repository for more info on that
- if applicable(for example for straming, converting...), use vlc.exe as an external process and don't use this lib.
