### ISSUE TITLE
How to get frame Bitmap?

### ISSUE THREAD

**Issue by wangning08115** [ZeBobo5/Vlc.DotNet#507]
I know can use vlcControl.TakeSnapshot(imgfile, (uint)size.Width, (uint)size.Height);
To get a Image file, And then read the file from disk,
But i dont want to TakeSnapshot save to disk, I only want to Get Bitmap in Memory,
then i can use Bitmap to show on UI my self.

**Comment by wangning08115** [comment]
I see the Vlc.DotNet.Wpf， It use below code:
```
 this.VideoSource = (InteropBitmap)Imaging.CreateBitmapSourceFromMemorySection(handle,
                    (int)args.width, (int)args.height, args.pixelFormat, (int)args.pitches, 0);
```
But i dont get a Bitmap object, I want get Bitmap object, And edit the Bitmap object, Such as add logo, add text ,add other image logo To the Bitmap object.

**Comment by wangning08115** [comment]
Thanks for jeremyVignelles ：
I use "how-to-convert-interopbitmap-to-bitmap" , And Run Right, 
But a important Error throw,  When "GetBitmap" function run more than 20 min, 30min , 
The return Bitmap result si always one same Picture Bitmap , No longer update, 
And throw error log below:
`[00000171fbb17f70] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[00000171fc5d76e0] main vout display error: Failed to set on top
[00000171fc5d76e0] main vout display error: Failed to set on top
[00000171fc5871c0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)`

My GetBitmap fcuntion s below:
```

Bitmap GetBitmap(BitmapSource source)
{
            Bitmap bmp = new Bitmap(
              source.PixelWidth,
              source.PixelHeight,
              System.Drawing.Imaging.PixelFormat.Format32bppPArgb);
            BitmapData data = bmp.LockBits(
              new System.Drawing.Rectangle(System.Drawing.Point.Empty, bmp.Size),
              ImageLockMode.WriteOnly,
              System.Drawing.Imaging.PixelFormat.Format32bppPArgb);
            source.CopyPixels(
              Int32Rect.Empty,
              data.Scan0,
              data.Height * data.Stride,
              data.Stride);
            bmp.UnlockBits(data);
            return bmp;
}
```

**Comment by jeremyVignelles** [comment]
I don't think that it's a good idea for perfs 'to stack layers of copies like that.
Please reimplement your own video callback by taking example on Vlc.DotNet.Wpf

**Comment by wangning08115** [comment]
Yes reimplement my own video callback as below code:
`        private void DisplayVideo(IntPtr userdata, IntPtr picture)
        {
#if NET45
            Bitmap tempRenderCacheFrameBitmap = new Bitmap(1280, 720, System.Drawing.Imaging.PixelFormat.Format32bppRgb);
            BitmapData bmpData = tempRenderCacheFrameBitmap.LockBits(new Rectangle(0, 0, 1280, 720),
                                                  ImageLockMode.ReadWrite,
                                                  System.Drawing.Imaging.PixelFormat.Format32bppRgb);
            /* Copy the memory from the sample pointer to our bitmap pixel pointer */
            /* Get the pointer to the pixels */
            IntPtr pBmp = bmpData.Scan0;

            int pSize = 1280 * 32 / 8 * 720;
            //Copy Data to Bitmap
            CopyMemory(pBmp, userdata, pSize);

            tempRenderCacheFrameBitmap.UnlockBits(bmpData);
            //RenderCacheFrameBitmapQueue Is a queue to save TempRenderCacheFrameBitmap Bitmap, And i start a new Thread to get bitmap from RenderCacheFrameBitmapQueue
            RenderCacheFrameBitmapQueue.Enqueue(tempRenderCacheFrameBitmap);
#endif
        }`

My error is: when run app more than 20 min,Will get error from visual studio output window log:
`[000001cff2612d20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001cff285a6c0] main vout display error: Failed to set on top
[000001cff2826380] main vout display error: Failed to set on top
[000001cff2665ba0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
[000001cff2665ba0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)`

And " CopyMemory(pBmp, userdata, pSize);" will get same data from "IntPtr userdata" forever.
And the bitmap resault is a always one same Picture.

**Comment by jeremyVignelles** [comment]
Do you experience the same issue with Vlc.DotNet.Wpf itself?
I don't know what this error is, but you video is likely too heavy for your computer's ressources. what are you trying to achieve?

**Comment by Mamad4D** [comment]
hi jeremy, 
is there anyway to get frame by "Vlc.DotNet.Forms" instead of "Vlc.DotNet.Wpf"?
Because "vlc" performs less **processing** in "win" than "wpf".
for example "cpu" **usage** in "winform" is 1% but in "wpf" is about 12%.
I do not like TakeSnapshot function, I need the frame as a Stream
Thanks

**Comment by wangning08115** [comment]
Yes Yes，I also need an High performs Style To get frame in background Thread.
Know i use Vlc.DotNet.Wpf code, But It low performs.

**Comment by jeremyVignelles** [comment]
@Mamad4D : You won't be able to get decoded frames in a fast way.
When you display a video on your screen, the WinForms control (through libvlc) takes a hardware-accelerated shortcut using DirectX:
- A few frames are decoded in your graphic card using hardware acceleration.
- At the specified time, the graphic card directly takes that decoded frame from its memory directly to your screen.

All that happens in your graphic card and doesn't need to copy the buffer into the RAM (which takes many CPU cycles), and the GPU -> RAM copy is not instant, especially at high resolutions.
After that, the Wpf control takes those frames and send them back to DirectX for rendering, copying it back to the GPU, because there is no other way to do in WPF.

This is why you see a high CPU usage : the copy takes CPU power, and there's nothing you can do about it.

As soon as you need to copy the buffer, you will kill the performance and won't be able to decode at 60fps.

Take snapshot won't help you get all frames, and suffers from the same issues as the video callbacks : it needs to copy the frames to the RAM to be accessible in your program.

@wangning08115 and @Mamad4D : I don't know what you are trying to achieve, but this seems like the wrong way to do it : Decoded frames are huge (take for example at 32 bits per pixel at 1080p, that makes 66MB per frame if I'm correct) and you will need to multiply that by the number of frames you decode. Encoding in JPEG will save you many bytes, but are you sure you want each frame?

If you want to integrate a watermark or something, you'd better use the VLC video filters and encoding capabilities.

**Comment by wangning08115** [comment]
@jeremyVignelles   Very thanks for your comment.

Why i want get every frame?
My system has an "face recognition" module,  Need input an Bitmap Data, Then "face recognition" module can return an Json String ,The Json include Face information, Such as Age,Sex,Face Location in Image. 
So i need every frame.

**Comment by jeremyVignelles** [comment]
@wangning08115 : Start by reducing the number of frame per seconds and the input resolution. Then, this method will likely be ok for your need.

I suppose that 5 images per second is enough for a face recognition scenario, isn't it?

**Comment by wangning08115** [comment]
Yes, 8 images per second can enough My requirements. 
I will try this.
I used VLC official WebSite C# Lib  before, And i set the number of frame Parameter, But this parameter is still invalid, It still return 15 frame per second.  
I will try "Vlc.DotNet" to use 8 images per second.
Thanks!

**Comment by Mamad4D** [comment]
@jeremyVignelles  Special thanks to you for the detailed description.
i need all frames (30fps / 50fps) for Image processing (ANPR software). this software use cpu and gpu (cuda framework) jointly.
as you know Cuda use Gpu very nice, Cuda has a class that named CudaImage.
Can i use vlc frames that placed on gpu for CudaImage?

**Comment by masgh021** [comment]
@jeremyVignelles  
IS IT POSSIBLE MAKE A SAMPLE FOR GET FRAME 
IN WINFORM .NET FRAMEWORK ????

**Comment by mfkl** [comment]
Why are you yelling? See https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Samples/Samples.Core.Thumbnailer/Program.cs
