### ISSUE TITLE
example for SetVideoCallbacks function in winForm

### ISSUE THREAD

**Issue by Mamad4D** [ZeBobo5/Vlc.DotNet#522]
hi 
i need an **example** for SetVideoCallbacks function in winForm to get video frame by frame.

**Comment by jeremyVignelles** [comment]
Please don't spam, this issue is enough.

This file is a good place to start:
https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs

This is the WPF implementation, but the logic is the same.

The key is to use these lines and implement the callbacks accordingly:
https://github.com/ZeBobo5/Vlc.DotNet/blob/fb42e9a59950fcc27738d0f36477812727ee2152/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs#L111-L112

See the documentation here : 
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga612605f2e5c638d9f4ed59021d714bf0
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#gafbeef69fb76b4c4d6cb25145aee1ad99

**Comment by wangning08115** [comment]
This info is good.

**Comment by mg021** [comment]
Hello @jeremyVignelles  
i am new to vlc dotnet
i read wpf sample for setvideoCAllback
But i cant understand it. 
please make winform sample For Getting Every Frame From Video 
thanks

**Comment by jeremyVignelles** [comment]
Here is a sample I made for LibVLCSharp. The logic for Vlc.DotNet is the same.

This is a work in progress,because I failed to limit the fps for now, and the computer is struggling.

Moreover, the sample I wanted to do makes no sense : I wanted to create thumbnails of a video file, but playing the file to get thumbnail is a poorly optimised way to do so. If the video is 2 hours long, I can't imagine waiting that long to get thumbnails

**Comment by mg021** [comment]
@jeremyVignelles  
i need every frame From a rtsp Address
how get it ??? 
i work in winform

**Comment by jeremyVignelles** [comment]
You won't be able to do so with 4k@60fps stream, otherwise, you can try with the sample I gave you

**Comment by jeremyVignelles** [comment]
I think I answered the original question, closing this.
