### ISSUE TITLE
Catch unhandled exceptions from VLC

### ISSUE THREAD

**Issue by nafarkash** [ZeBobo5/Vlc.DotNet#561]
I have an a question about Vlc.DotNet.Core (Not sure)

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.7.1 x86 + VideoLAN.LibVLC.Windows from nuget package
- **.net version** : 4.5.2
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : Windows 10 x64

# Summary

**I got the following unhandled exception in one of VLC modules (from WindowsLogs)**
Faulting application name: XXXXXXX.exe, version: 3.2.0.0, time stamp: 0x5cea6fe8
Faulting module name: libstream_out_rtp_plugin.dll, version: 3.0.7.1, time stamp: 0x30d330a4
Exception code: 0x40000015
Fault offset: 0x0006ec67
Faulting process ID: 0x1098
Faulting application start time: 0x01d52cee47479f51
Faulting application path: C:\Program Files (x86)\XXXXXXX\XXXXXXX.exe
Faulting module path: C:\Program Files (x86)\XXXXXXX\libvlc\win-x86\plugins\stream_out\libstream_out_rtp_plugin.dll
Report ID: deeaee30-d7d0-474d-98f6-fb8ee93c096c
Faulting package full name: 
Faulting package-relative application ID: 

**Other useful information:** 

- The stream is from other machine in my network

- I can get numerous files to play - which I play as playlist and in a loop

Here is how I use the VLC: 
`VlcControlForClip.SourceProvider.MediaPlayer.Play(new Uri(clipsLocation[index]).AbsoluteUri, ":file-caching=" + file_caching);`

Of course it is wrapped up in try-catch, and moreover I register to `AppDomain.CurrentDomain.UnhandledException` as well to catch unhandled exceptions.

Despite all that - the error is still thrown.
I can't really tell what was the displayed video or weather it was legit or not - but still I wan't to catch and handle this exception in my code and not to be thrown out.

How can I do that?

Please tell me if any additional data is required
Thanks, 
Naor.

**Comment by jeremyVignelles** [comment]
The error you are seeing is a native crash (something like a VLC module trying to access an invalid pointer). You can't catch such crashes. The only way to solve this is to resolve the crash.

I can't really tell what's wrong without more info. Does that happen in VLC itself? Can you share a sample project reproducing the issue?

**Comment by nafarkash** [comment]
Thanks for the quick reply.
I'll alter the code and acquire additional information

**Comment by jeremyVignelles** [comment]
Anything new on your side?

**Comment by tigros** [comment]
I was looking for a solution and found this issue which was closed not too long ago.. Ima gonna post 2 dumps 1 of which is exactly as described above, the other is libfreetype_plugin!FT_Bitmap_Done

My app can run for days looping a playlist or w/e then all of sudden these crashes happen, so reproducing is not easy.

Any ideas?  
Thanks!

[mysys.exe.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/3513609/mysys.exe.zip)

**Comment by jeremyVignelles** [comment]
@tigros : did you mean to post on #559 ?

**Comment by tigros** [comment]
nope i didn't see 559, the error code is different here it's 0x40000015, 559 is 0xc0000374.

anyway it's likely a vlc C++ prob somewhere, i don't think i'm going to pursue that.. it's quite a rare occurrence, several days.

**Comment by jeremyVignelles** [comment]
@tigros : I'm still interested in your issue, because it seems very close to our case in 559 : stopping and starting a media player resulting in a crash on libvlc side.
It's rare in your case, but probably because your video is quite long/you don't switch very often.

Could you tell me what kind of video you're trying to play?
You're talking about freetype, are you using the marq plugin or displaying subtitles or something?

**Comment by tigros** [comment]
i'm pretty sure it's only happened while playing a playlist of .mp3/.flac, it closes vlc after a song, wait 1 sec, creates a new vlc for next song and crash around there.

**Comment by jeremyVignelles** [comment]
Using Vlc.DotNet, right? The freetype crash is weird then...

**Comment by tigros** [comment]
yes 3.0.6

**Comment by tigros** [comment]
it just happemed again but this time libadaptive_plugin!vlc_entry_license__3_0_0f+0x7fd9b

seems it's always vlc_entry_license but diff plugins, i searched the code and google not much info on it, nowhere in the code, what is it?

**Comment by tigros** [comment]
I was able to reproduce this bug while letting the app run from VS debug for a long time breaking on all exceptions.

The exception was:
Managed Debugging Assistant 'LoaderLock' 
  Message=Managed Debugging Assistant 'LoaderLock' : 'Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'

It was on `myVlcInstance = new VlcInstance(this, myLibraryLoader.GetInteropDelegate<CreateNewInstance>().Invoke(utf8Args.Length, utf8Args));` of Vlc.DotNet.Core.Interops\VlcManager.cs.

Continuing execution got the C++ crash and app closed.

So from that I found this: https://stackoverflow.com/a/31322244/990618

VlcManager.cs becomes:
```            
using System.Threading;
...
private VlcLibraryLoader myLibraryLoader;
private VlcInstance myVlcInstance;
...
	ThreadStart threadRef = new ThreadStart(() =>
	{
		this.myLibraryLoader = VlcLibraryLoader.GetOrCreateLoader(dynamicLinkLibrariesPath);
	});
	Thread myThread = new Thread(threadRef);
	myThread.IsBackground = true;
	myThread.Start();
	myThread.Join();
...
	threadRef = new ThreadStart(() =>
	{
		myVlcInstance = new VlcInstance(this, myLibraryLoader.GetInteropDelegate<CreateNewInstance>().Invoke(utf8Args.Length, utf8Args));
	});
	myThread = new Thread(threadRef);
	myThread.IsBackground = true;
	myThread.Start();
	myThread.Join();
```
Difficult to comprehend why this would work, explanations welcome, but so far so good!

I could be speaking too soon it's only been a day but if it crashes i'll post again, anyone who had the issue please try it out.
