### ISSUE TITLE
Option to cancel loading vlcControl.

### ISSUE THREAD

**Issue by Issung** [ZeBobo5/Vlc.DotNet#562]
I am having an issue with Vlc.DotNet in my Win Forms application.

On form load when 'VlcLibDirectoryNeeded' is fired I am giving the user the option to locate their vlc install directory or ignore this and continue without video functions support. But it seems I cannot do the ignore functionality because I cannot get the VlcControl to ignore this fact. At the moment I've tried removing the control from the form and disposing it, neither have worked. Is there any way I can remove the control or get it to just not load, the error happens in EndInit method from ISupportInitialize

- Vlc.DotNet version: 3.0.0
- Vlc.DotNet project used: WinForms
- libvlc version: x86, Got it with my standard vlc installation.
- .net version: 4.7.1
- Project language: C#
- Project build architecture: x86
- Operating system: Win10 64bit

This is not an issue with this library I am just looking for how to perform this functionality, if it is not possible can we possibly work it into this project?

Thanks in advance.

**Comment by jeremyVignelles** [comment]
Hi,
Thanks for reporting. At first, I was tempted to say that we could just pass a boolean in the event args and handle that in the library, but I fear that the incomplete initialization would cause issues.

I think that the best way is to open your own dialog beforehand, and create the VlcControl afterwards and add it to your view. When doing this, you don't even need the DirectoryNeeded event, since there is a propery you can set before calling EndInit()

**Comment by jeremyVignelles** [comment]
That being said, the event-based API should have a proper way to "cancel", because if someone doesn't have a VLC on his machine... I'm not sure how do people are handling this currently...

**Comment by Issung** [comment]
Maybe worth some thought, It would be nicer than having to dynamically create them all the time in my project. I even have one form that has 2 VlcControls playing simultaneously, it would be a pain to have to dynamically create them both. If there was a property on the 'VlcLibDirectoryNeededEventArgs' class perhaps called 'ignore' or maybe setting the 'VlcLibDirectory' property to null...

**Comment by jeremyVignelles** [comment]
This is the code that calls the `VlcLibDirectoryNeeded` event:
https://github.com/ZeBobo5/Vlc.DotNet/blob/a63a6f5de23fa660bbd2b4221ffd810f95167df1/src/Vlc.DotNet.Forms/VlcControl.cs#L94

When you set `VlcLibDirectory` to null in the callback, an exception is thrown.
After reading through the file, I think that every reference to `myVlcMediaPlayer` is checked for null before using. In theory, we could replace that `throw ...` by a `return` without harming the code.

However, doing that is a breaking change for users that are catching this exception, and I'm not sure that this is really a nice thing to do.

I'm not really sure that asking the user for a folder during initialization is the right thing to do for the User eXperience. I'd rather let him the choice far before the VideoView initialization, and save that in a setting on the disk. If he does provide a valid path, only then you can create a VideoView and initialize it (and then you don't need the callback either, since there is a `VlcLibDirectory` property)

Closing as won't fix, since code provides a more flexible alternative to the designer already.
Feel free to continue asking questions 🙂
