### ISSUE TITLE
Subscribe to Videosource.Changed event

### ISSUE THREAD

**Issue by daveMueller** [ZeBobo5/Vlc.DotNet#563]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : 3.0.7.1 + VideoLAN.LibVLC.Windows from nuget package
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows x64

# Summary

I've got an WPF application and want to subscribe to ```VideoSource.Changed``` after the main windows is loaded. The ```VlcVideoSourceProvider``` is instantiated in the ```MainWindow``` constructor and ```MediaPlayer``` is started immediately.

```
public MainWindow()
{
	InitializeComponent();
	var currentAssembly = Assembly.GetEntryAssembly();
	var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
	var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

	_sourceProvider = new VlcVideoSourceProvider(this.Dispatcher);

	_sourceProvider.CreatePlayer(libDirectory);
	ThreadPool.QueueUserWorkItem(x => _sourceProvider.MediaPlayer.Play(new Uri("rtp://192.168.99.1:5004")));
}
```

Now when I subscribe after ```MainWindow``` is loaded the ```Videosource``` is still ```null```. 

```
private void Window_Loaded(object sender, RoutedEventArgs e)
{
	_sourceProvider.VideoSource.Changed += VideoSourceChanged;
}
```

When I wait a certain amount of time before subscribing (approx. 3-4 sec) the ```VideoSource``` isn't null anymore and everthing works fine.

Is it somehow possible that the ```VlcVideoSourceProvider``` tells me that it's now possible to subscribe to the ```VideoSource```?

**Comment by jeremyVignelles** [comment]
`VideoSource.Changed` is not something that is implemented here, but I suspect that it will trigger each time a new frame is available. Is it really what you want?

> Is it somehow possible that the VlcVideoSourceProvider tells me that it's now possible to subscribe to the VideoSource?

I suspect you are looking for : 
```
_sourceProvider.PropertyChanged += (s, e) => {
   if(e.PropertyName == "VideoSource")
   {
      // Do something with _sourceProvider.VideoSource
   }
};

**Comment by daveMueller** [comment]
Thanks, the solution you provided works fine.
 
Yes that's exactly what I want to do. I need to grab every frame for a certain amount of time to support a feature we implemeted using a hardware framegrabber. Do you have a better solution how I could realize the frame grabbing?

**Comment by jeremyVignelles** [comment]
If you don't need to display the frames, I would recommend that you replace the VideoSourceProvider and that you implement the video callback yourself (otherwise, you will have one more copy that would slow down the process):

Start with those two lines : https://github.com/ZeBobo5/Vlc.DotNet/blob/a63a6f5de23fa660bbd2b4221ffd810f95167df1/src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs#L111-L112

That way, you can pick the video size you want, and be notified by VLC directly when a new frame is available.

Be careful though, don't make your heavy computations inside the callback, or you will block the libvlc thread. Defer them for later.
Another advice, you can reduce the frame rate of your video to reduce the number of frames to analyze.

**Comment by daveMueller** [comment]
Thanks a lot, I got it to work. :thumbsup:
