### ISSUE TITLE
[Question] No hw acceleration for Vlc.DotNet.Wpf with IsAlphaChannelEnabled, but no alpha channel support for Vlc.DotNet.WinForms

### ISSUE THREAD

**Issue by ManticSic** [ZeBobo5/Vlc.DotNet#596]
I have an a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms/WPF
- **libvlc version** : 3.0.8.1 x64 + VideoLan.LibVLC.Windows package
- **.net version** : .NET Framework 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary

I have an application where I want to display a video with an alpha channel. Currently I'm using mov (Apple ProRes 4444).   
If I use Vlc.DotNet.WPF unfortunately the video is processed by CPU.  
If I use Vlc.DotNet.WinForms with WindowsFormsHost the performance is much better, but the alpha channel isn't displayed (black background).

Is there any way to use hardware acceleration and Vlc.DotNet.WPF (or the alpha channel)?
Or using Vlc.DotNet.WinForms with alpha channel support?

The alpha channel only works with mov. Is webm with VP9 not supported? Or can you suggest any other format which supports transparency and works with Vlc.DotNet?

**Comment by jeremyVignelles** [comment]
Hi,
Unfortunately, I don't think that's possible. First of all, I don't know if libvlc does support displaying a video with an alpha channel in a win32 windows.

But most importantly, the very nature of WinForms embedded in WPF, I'm pretty sure that you can't do that, because WinForms and WPF have two different incompatible ways of rendering things. Here is an answer I found after a quick search on the topic : https://stackoverflow.com/a/8295909/2663813

**Comment by ManticSic** [comment]
Okay, thx for your fast response.  
So I have to stuck with Vlc.DotNet.WPF. 

Do anyone know a way to force hw acceleration?  
After a search I found this post: https://stackoverflow.com/questions/34675182/how-to-enable-hardware-accelerated-decoding-in-libvlc
but adding `avcodec-hw=dxva` or `avcodec-hw=dxva2` as a param to `mediaplayer.setMedia` has no impact for me (only tested on one device)

**Comment by jeremyVignelles** [comment]
Totally forgot about this topic. You can't use hw acceleration if you're using the WPF control, because the image needs to be decoded into RAM in order to be displayed.

I think that you need to dig deeper inside VLC and/or win32 apis. Either there is a way to tell a HWND to have a transparent background, or libvlc draws a black background anyway, and you can't do anything about it, but recompiling it.

I'm going to close this for now. Feel free to reopen if you need something else
