### ISSUE TITLE
How to use LibVLCSharp make a Video Provider like VlcVideoSourceProvider.cs !!

### ISSUE THREAD

**Issue by zdy1988** [ZeBobo5/Vlc.DotNet#688]
**LibVLCSharp.WPF** is a **WindowsFormsHost**，and the **WindowsFormsHost** is always the most top from WPF element ...

and Vlc.DotNet.WPF ‘s solution is more perfect...

How to use **LibVLCSharp** make a Video Provider like **VlcVideoSourceProvider.cs** !!

**Comment by jeremyVignelles** [comment]
This is a question for LibVLCSharp, not this repository.
We do want to have such sample in LibVLCSharp, but we don't want to make it the default view because of performance.

Help is welcome : you have the way it's done il Vlc.DotNet, you have the Thumbnailer samples in LibVLCSharp samples, so you have everything you need to create the sample and send us a PR.
