### ISSUE TITLE
TakeSnapShot with stream parameter?

### ISSUE THREAD

**Issue by TizzyT566** [ZeBobo5/Vlc.DotNet#695]
I have a question about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.1.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 nuget
- **.net version** : framework 4.8
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary

I was wondering how one goes about taking a snapshot to a stream instead of a file on disk. There are no overloads which take a stream as an argument nor does it take a bitmap as a ref/out param. I was just wondering how can a snapshot be obtained without having to write to disk first. I know its a long shot for what this is but just asking to cover all bases.

- [ N/A ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
This is because libvlc 3 doesn't support it : it writes directly to the disk.
Libvlc 4 has an API for that, but it will not be supported by this library unfortunately.

I don't know if it is currently supported by LibVLCSharp 4 preview, but if it's not, that's something worth implementing.

/cc @mfkl
