### ISSUE TITLE
How do i simply play a video and get past the barrage of error messages.

### ISSUE THREAD

**Issue by akumakuja28** [ZeBobo5/Vlc.DotNet#704]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : Current NuGet (jan-17-2022)
- **Vlc.DotNet project used** : Win Forms / Console
- **libvlc version** : (VLC 3.0.9.2
- **.net version** : 6.0
- 
- **Project language** : (C#/VB.net)
- **Project build architecture** : (x86/x64/AnyCPU/AnyCPU (prefer 32bits))
- **Operating system** : (Windows 10) (x86/x64)

# Summary

I have been all over google for the past 3 hours trying to get this bloated project to just work. The Console App Example fails with a Fatal error. 0xC0000005

 var mediaPlayer = new Vlc.DotNet.Core.VlcMediaPlayer(libDirectory); Says memory corrupt

The Example dont work. Seriously tho. 

Moving on to windows Forms. Constant Error with 
         vlcControl1.EndInit();  
---------- Attempt to read or write protected memory. 

Minor Rant Here: What is the issue with so many github repositories lacking in simple working examples. If you cant have a working cut and paste example of code, your page should honestly be red flagged. I shouldnt have to dive into stackoverflow for usage examples of your posted code.

**Comment by jeremyVignelles** [comment]
A few things here:
- You're asking a question to a project in maintenance mode, please consider switching to LVS instead
- You didn't fill the issue template properly
- You're just ranting about the project with no respect to the hours spent here trying to make things work.
- The sample does work, otherwise the issue would have been posted before
- Did you have a look at [the wiki page](https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started) before claiming there is no copy/paste example ?
- Try upgrading the libvlc nuget package to a more recent version. It's possible that the libvlc version was broken by a windows update at some point. As I said earlier, the sample project was not updated because I do not work on this project anymore.
- If you find this project `bloated`, then feel free to find another implementation or to implement a libvlc binding yourself. Also, please define "bloated".

**Comment by akumakuja28** [comment]
I get you closed it and I am still going to respond here as i did get working and found the "my" issue. Maybe it was my ignorance here with netcore vs .net. IDK if you listed this issue or not and I am sorry for not looking. 

netcore 6.0 based form apps grey out VlcLibDirectory in form designer. 
Sample code for console app does not work in netcore6.0 

Currently code Is working in .Net Framework. My apologies again.  

Sorry for calling it bloated.
