### ISSUE TITLE
I want to know how to play UDP Media

### ISSUE THREAD

**Issue by lebhero** [ZeBobo5/Vlc.DotNet#82]
Hi..
in the wpf sample provided, i want to play udp media.
Before i change the code i tried the following:
i opened up 2 vlc instances, and streamed from instance a video on the local machine, and on the other i opened the stream.
I had success receing the video over udp on the the 2nd instance

so back to the wpf sample provided,
i entered exactly the same address as i gave in vlc (udp://@:1234)

``` cs
myControl.MediaPlayer.Play(new Uri("udp://@:1234"));
```

but iam having an exception:
An unhandled exception of type 'System.UriFormatException' occurred in System.dll
Additional information: Invalid URI: The hostname could not be parsed.

Can anyone please tell me how to open udp streams in the wpf example provided?
thanks in advance

**Comment by jmarcorb** [comment]
Ok, I was looking for something similar, as I could play rtp streams but could not play udp streams, and for rtp I was getting the same exception (that had nothing to do with Vlc.Dotnet), as I was trying to use a similar string that is used in vlc itself: 
<code>new Uri("rtp://@:5004") // --> this throws the same exception.</code> 
It seems Uri needs a clear IP address, because when I tried:
<code>new Uri("rtp://local-ip-of-the-client-machine:5004") //--> works!!</code>
it all worked like a breeze. Of course, the next thing I did was to try the same in udp streams, but to no avail. No exception but no video playing.

The answer came doing further research on the internet. I saw someone using "@local-ip-of-the-client-machine" on some other vlc applications in udp streams and said... what the hell.. lets try this.
<code>new Uri("udp://@local-ip-of-the-client-machine:5004")   //--> also works!</code>
Notice the (at) before local ip address.

Hope that helps!

**Comment by jeremyVignelles** [comment]
This is not a Vlc.DotNet limitation, but the way an URI is meant to be written. Vlc uses a slightly different concept : mrl. what you are trying to pass is a vlc-specific syntax to an Uri object, which fails. 
As of 2017, you can use the Play overload with a string parameter.
