### ISSUE TITLE
Cant OPEN MRL (rtsp)

### ISSUE THREAD

**Issue by 3Passer** [ZeBobo5/Vlc.DotNet#9]
I tried to open a rtsp URI with the sample. the URi works in the direkt VLC Player.

The Sample puts this to the Debugviewer:
[12172] main input error: open of `rtsp://192.168.99.132:8554/' failed
[12172] main input error: Your input can't be opened
[12172] main input error: VLC is unable to open the MRL 'rtsp://192.168.99.132:8554/'. Check the log for details.

via Wireshark:
the "Options"-Request is sent, the response also seems to be correct, 
but no Describe setup and so on is sent by the sample

**Comment by 3Passer** [comment]
with the most current plugin folder from vlc dir the problem was solved

**Comment by Kradhox** [comment]
Same here, I can't open rtsp URI.

My URI works perfectly with VLC Player but when I try to open the same URI with Vlc.DotNet the EncounteredError event is raised.

My URI looks like this : rtsp://192.168.115.147:554/10848614165810278027?device=4

Here is what I see with Wireshark :

VLC Player : 
Method : OPTIONS 
URL : rtps://192.168.115.147:554/10848614165810278027?device=4
User-Agent : LibVLC/2.1.5 (LIVE555 Streaming Media v2014.05.27)

Vlc.DotNet : 
Method : OPTIONS 
URL : rtps://192.168.115.147:554
User-Agent : RealMedia Player Version 6.0.9.1235 (linux-2.0-libc6-i386-gcc2.95)

Both responses have status 200.
I don't understand why the query part of my URI simply disappeared and why is RealMedia Player used instead of live555.

I'm already stuck for days.

**Comment by ZeBobo5** [comment]
The most simple is to ask about this problem on VLC Forum. I think, this not a Vlc.DotNet problem but a LibVlc problem.

**Comment by Kradhox** [comment]
Yes, you're right.

After a lot of debuging, it's apparently a problem with the use of the 64bits DLL of VLC.
So if somebody else has the same problem, simply use the 32bits version of VLC ;)

PS: thanx a lot ZeBobo5 for this DotNet wrapper of libvlc, by far the most simple to use and to understand on the internet.

**Comment by ZeBobo5** [comment]
Thanks for your support
