### ISSUE TITLE
cannot mute, on start playing.

### ISSUE THREAD

**Issue by MeTaXaS4** [ZeBobo5/Vlc.DotNet#94]
i'm using this function to start the mediafile, but cannot set the volume to 0 or just mute.
if i try from another function to stop the audio stops.
 any idea?

```
    private void StartCapture(Vlc.DotNet.Forms.VlcControl mediaplayer, string ip)
    {
        try
        {
            if (mediaplayer.VlcLibDirectory != null && mediaplayer.IsPlaying)
            {
                mediaplayer.Stop();
            }
            else
            {
                mediaplayer.Play(new Uri(ip));
                mediaplayer.Audio.Volume = 0;

                mediaplayer.Audio.IsMute = true;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show("vlcControl : " + ex.Message + " connection string : " + ip);
        }
    }
```

**Comment by miaolinvip** [comment]
I have same problem,too!

**Comment by danielkurtz** [comment]
The last comment was over a year ago, but this issue still exists. The issue seems to be that muting and/or changing the volume does not seem to have any effect if the call is made prior to video starting to play, at least in the case of a streaming video. In fact, while debugging, I can see that the value for Volume is -1 initially and does not retain any value you set prior to playing. Once the video starts playing, this value changes to 100 even if I set Volume to 0 or IsMute.

The workaround that I employed involves the following:

- set a flag to true indicate that the audio should be muted initially

- add a handler for PositionChanged

- set Volume to 0 (or you could set IsMute to true) if the flag is true within the handler for PositionChanged

- if the user raises the volume or unmutes, set the flag to false to allow normal operation

The PositionChanged handler is called frequently so I experimented with the Playing, MediaChanged, Opening, and PausableChanged handler, but they were all called too early to set the Volume. The Buffering handler was called too early in some cases, but I was concerned that the video would start playing prior to being able to set the Volume to 0. Alternatively, if you're not doing anything else in the PositionChanged handler, you could unregister the handler after you're satisfied that the Volume has been muted. There may be another handler that works better, but I didn't encounter one.

**Comment by sigged** [comment]
I have the same issue with **local** video and audio. The workaround using VideoOutChanged offers a possible solution for video, but not for audio.

**Comment by jeremyVignelles** [comment]
Probably caused by an older version of libvlc, but libvlc 3.0 seems to suffer of another related issue, see #381 . Please correct me and reopen if I'm wrong.

**Comment by hippyau** [comment]
I ended up getting around this by busy-waiting for libvlc_media_player_get_state to change to playing, then immediately busy-wait for libvlc_audio_set_volume to return > -1.  

It seems to have helped a lot, though it takes me on average 10ms in busy-waiting (local media, not tried streaming).

It's still not right working as i'd hoped on 3.0.5. 

Thanks for VLC by the way, it's awesome!

**Comment by jeremyVignelles** [comment]
@hippyau : you can handle the Playing event instead of busy-waiting for the state to be playing
